core/web_app/urls.py
from django.conf.urls import url

from core.web_app import views

urlpatterns = [
    url('^$', views.IssueListView.as_view(), name='list_issues'),
    url('^issues/$', views.IssueFormView.as_view(), name='manage_issues'),
    url('^issues/(?P<issue_id>\d+)/$', views.IssueFormView.as_view()),
    url('^issues/(?P<issue_id>\d+)/finish/$', views.FinishIssueView.as_view(), name='finish_issue'),
]

sac/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'', include('core.web_app.urls', namespace='core')),
]

core/models.py
from .web_app.models import Issue

core/web_app/models/issue.py
# coding: utf-8
from django.db import models


class Issue(models.Model):

    source_id = models.PositiveIntegerField()
    location_id = models.PositiveIntegerField()
    subject_id = models.PositiveIntegerField()
    description = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(null=True)

core/web_app/forms/issue_form.py
# coding: utf-8
from django import forms

from core.domain.collections import LOCATIONS, SOURCES, SUBJECTS
from core.web_app.models import Issue


class IssueForm(forms.ModelForm):

    DEFAULT_CHOICE = [('', '--------')]

    source_id = forms.TypedChoiceField(label=u'Origem', choices=DEFAULT_CHOICE + SOURCES, coerce=int)
    location_id = forms.TypedChoiceField(label=u'Estado', choices=DEFAULT_CHOICE + LOCATIONS, coerce=int)
    subject_id = forms.TypedChoiceField(label=u'Assunto', choices=DEFAULT_CHOICE + SUBJECTS, coerce=int)
    description = forms.CharField(label=u'Descrição', max_length=1000, widget=forms.Textarea)
    finished_at = forms.CharField(label=u'Encerrado em', disabled=True, required=False)

    class Meta:
        model = Issue
        fields = ('source_id', 'location_id', 'subject_id', 'description', 'finished_at')

core/web_app/views/issue_view.py
# coding: utf-8
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import FormView, ListView, View

from core.use_cases import CreateIssueUseCase, FinishIssueUseCase, IssueReportUseCase
from core.web_app.daos import IssueDao
from core.web_app.formatters import AggregateIssues
from core.web_app.forms import IssueForm
from core.web_app.models import Issue


class IssueFormView(FormView):

    form_class = IssueForm
    template_name = 'create_or_update_issue.html'
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super(IssueFormView, self).get_form_kwargs()

        issue_id = self.kwargs.get('issue_id')
        if issue_id:
            kwargs['instance'] = get_object_or_404(Issue, id=issue_id)
        return kwargs

    def form_valid(self, form):
        use_case = CreateIssueUseCase(IssueDao())
        data = form.cleaned_data
        data.pop('finished_at')

        use_case.execute(**data)

        return super(IssueFormView, self).form_valid(form)


class IssueListView(ListView):

    template_name = 'list_issue.html'

    def get_queryset(self):
        use_case = IssueReportUseCase(IssueDao(), AggregateIssues)
        return use_case.execute()


class FinishIssueView(View):

    def get(self, request, *args, **kwargs):
        issue_id = kwargs.get('issue_id')
        use_case = FinishIssueUseCase(IssueDao())

        use_case.execute(issue_id)

        return JsonResponse({})

core/web_app/templates/create_or_update_issue.html
{% extends 'base.html' %}
{% load form_filters %}

{% block navbar %}
<li><a href="{% url 'core:list_issues' %}">Relatórios</a></li>
<li class="active"><a href="{% url 'core:manage_issues' %}">Novo Chamado</a></li>
{% endblock %}

{% block content %}
  <h1 class="page-header">Novo Chamado</h1>
  <form action="{% url 'core:manage_issues' %}" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group {% if field.errors %}has-danger{% endif %}">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>

      {% if field.errors %}
        {% for error in field.errors %}
        {{ field|css_class:'form-control form-control-danger' }}
        <div class="form-feedback">{{ error|escape }}</div>
        {% endfor %}
      {% else %}
        {{ field|css_class:'form-control' }}
      {% endif %}

      <small class="form-text text-muted">{{ field.help }}</small>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock %}

core/web_app/templates/list_issue.html
{% extends 'base.html' %}
{% block navbar %}
<li class="active"><a href="{% url 'core:list_issues' %}">Relatórios</a></li>
<li><a href="{% url 'core:manage_issues' %}">Novo Chamado</a></li>
{% endblock %}

{% block content %}
  <h1 class="page-header">Relatório</h1>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Data</th>
        </tr>
      </thead>
      <tbody>
        {% for date_group in object_list %}
        <tr>
          <td>
            {{ date_group.created_at }}
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Estado</th>
                </tr>
              </thead>
              <tbody>
              {% for location_group in date_group.items %}
                <tr>
                  <td>
                    {{ location_group.location }}
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>Assunto</th>
                          <th>Origem</th>
                          <th>Descrição</th>
                          <th>Ação</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for issue in location_group.items %}
                        <tr>
                          <td>{{ issue.subject }}</td>
                          <td>{{ issue.source }}</td>
                          <td>{{ issue.description }}</td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt">
  <head>
    {% include 'includes/head_tags.html' %}
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">SAC - Serviço de Atendimento ao Cliente</a>
        </div>
      </div>
    </nav>
    <div class="container -fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            {% block navbar %}
            <li class="active"><a href="{% url 'core:list_issues' %}">Relatórios</a></li>
            <li><a href="{% url 'core:manage_issues' %}">Novo Chamado</a></li>
            {% endblock %}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% block content %}
        <h1 class="page-header">Dashboard</h1>
        {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/head_tags.html
<meta charset="utf-8">
<title></title>
{% load staticfiles %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
<link rel="stylesheet" href="{% static 'css/form.css' %}" />